/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.41).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.SecurityConfiguration;
import io.swagger.model.SwaggerResource;
import io.swagger.model.UiConfiguration;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-02-28T07:12:51.688625534Z[GMT]")
@Validated
public interface SwaggerResourcesApi {

    @Operation(summary = "", description = "", tags={ "api-resource-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", schema = @Schema(implementation = SecurityConfiguration.class))) })
    @RequestMapping(value = "/swagger-resources/configuration/security",
        produces = { "*/*" }, 
        method = RequestMethod.POST)
    ResponseEntity<SecurityConfiguration> securityConfiguration();


    @Operation(summary = "", description = "", tags={ "api-resource-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", schema = @Schema(implementation = SecurityConfiguration.class))) })
    @RequestMapping(value = "/swagger-resources/configuration/security",
        produces = { "*/*" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<SecurityConfiguration> securityConfiguration1();


    @Operation(summary = "", description = "", tags={ "api-resource-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", schema = @Schema(implementation = SecurityConfiguration.class))) })
    @RequestMapping(value = "/swagger-resources/configuration/security",
        produces = { "*/*" }, 
        method = RequestMethod.GET)
    ResponseEntity<SecurityConfiguration> securityConfiguration2();


    @Operation(summary = "", description = "", tags={ "api-resource-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", schema = @Schema(implementation = SecurityConfiguration.class))) })
    @RequestMapping(value = "/swagger-resources/configuration/security",
        produces = { "*/*" }, 
        method = RequestMethod.PATCH)
    ResponseEntity<SecurityConfiguration> securityConfiguration3();


    @Operation(summary = "", description = "", tags={ "api-resource-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", schema = @Schema(implementation = SecurityConfiguration.class))) })
    @RequestMapping(value = "/swagger-resources/configuration/security",
        produces = { "*/*" }, 
        method = RequestMethod.HEAD)
    ResponseEntity<SecurityConfiguration> securityConfiguration4();


    @Operation(summary = "", description = "", tags={ "api-resource-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", schema = @Schema(implementation = SecurityConfiguration.class))) })
    @RequestMapping(value = "/swagger-resources/configuration/security",
        produces = { "*/*" }, 
        method = RequestMethod.PUT)
    ResponseEntity<SecurityConfiguration> securityConfiguration5();


    @Operation(summary = "", description = "", tags={ "api-resource-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", schema = @Schema(implementation = SecurityConfiguration.class))) })
    @RequestMapping(value = "/swagger-resources/configuration/security",
        produces = { "*/*" }, 
        method = RequestMethod.OPTIONS)
    ResponseEntity<SecurityConfiguration> securityConfiguration6();


    @Operation(summary = "", description = "", tags={ "api-resource-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", array = @ArraySchema(schema = @Schema(implementation = SwaggerResource.class)))) })
    @RequestMapping(value = "/swagger-resources",
        produces = { "*/*" }, 
        method = RequestMethod.POST)
    ResponseEntity<List<SwaggerResource>> swaggerResources();


    @Operation(summary = "", description = "", tags={ "api-resource-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", array = @ArraySchema(schema = @Schema(implementation = SwaggerResource.class)))) })
    @RequestMapping(value = "/swagger-resources",
        produces = { "*/*" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<List<SwaggerResource>> swaggerResources1();


    @Operation(summary = "", description = "", tags={ "api-resource-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", array = @ArraySchema(schema = @Schema(implementation = SwaggerResource.class)))) })
    @RequestMapping(value = "/swagger-resources",
        produces = { "*/*" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<SwaggerResource>> swaggerResources2();


    @Operation(summary = "", description = "", tags={ "api-resource-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", array = @ArraySchema(schema = @Schema(implementation = SwaggerResource.class)))) })
    @RequestMapping(value = "/swagger-resources",
        produces = { "*/*" }, 
        method = RequestMethod.PATCH)
    ResponseEntity<List<SwaggerResource>> swaggerResources3();


    @Operation(summary = "", description = "", tags={ "api-resource-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", array = @ArraySchema(schema = @Schema(implementation = SwaggerResource.class)))) })
    @RequestMapping(value = "/swagger-resources",
        produces = { "*/*" }, 
        method = RequestMethod.HEAD)
    ResponseEntity<List<SwaggerResource>> swaggerResources4();


    @Operation(summary = "", description = "", tags={ "api-resource-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", array = @ArraySchema(schema = @Schema(implementation = SwaggerResource.class)))) })
    @RequestMapping(value = "/swagger-resources",
        produces = { "*/*" }, 
        method = RequestMethod.PUT)
    ResponseEntity<List<SwaggerResource>> swaggerResources5();


    @Operation(summary = "", description = "", tags={ "api-resource-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", array = @ArraySchema(schema = @Schema(implementation = SwaggerResource.class)))) })
    @RequestMapping(value = "/swagger-resources",
        produces = { "*/*" }, 
        method = RequestMethod.OPTIONS)
    ResponseEntity<List<SwaggerResource>> swaggerResources6();


    @Operation(summary = "", description = "", tags={ "api-resource-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", schema = @Schema(implementation = UiConfiguration.class))) })
    @RequestMapping(value = "/swagger-resources/configuration/ui",
        produces = { "*/*" }, 
        method = RequestMethod.POST)
    ResponseEntity<UiConfiguration> uiConfiguration();


    @Operation(summary = "", description = "", tags={ "api-resource-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", schema = @Schema(implementation = UiConfiguration.class))) })
    @RequestMapping(value = "/swagger-resources/configuration/ui",
        produces = { "*/*" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<UiConfiguration> uiConfiguration1();


    @Operation(summary = "", description = "", tags={ "api-resource-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", schema = @Schema(implementation = UiConfiguration.class))) })
    @RequestMapping(value = "/swagger-resources/configuration/ui",
        produces = { "*/*" }, 
        method = RequestMethod.GET)
    ResponseEntity<UiConfiguration> uiConfiguration2();


    @Operation(summary = "", description = "", tags={ "api-resource-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", schema = @Schema(implementation = UiConfiguration.class))) })
    @RequestMapping(value = "/swagger-resources/configuration/ui",
        produces = { "*/*" }, 
        method = RequestMethod.PATCH)
    ResponseEntity<UiConfiguration> uiConfiguration3();


    @Operation(summary = "", description = "", tags={ "api-resource-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", schema = @Schema(implementation = UiConfiguration.class))) })
    @RequestMapping(value = "/swagger-resources/configuration/ui",
        produces = { "*/*" }, 
        method = RequestMethod.HEAD)
    ResponseEntity<UiConfiguration> uiConfiguration4();


    @Operation(summary = "", description = "", tags={ "api-resource-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", schema = @Schema(implementation = UiConfiguration.class))) })
    @RequestMapping(value = "/swagger-resources/configuration/ui",
        produces = { "*/*" }, 
        method = RequestMethod.PUT)
    ResponseEntity<UiConfiguration> uiConfiguration5();


    @Operation(summary = "", description = "", tags={ "api-resource-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", schema = @Schema(implementation = UiConfiguration.class))) })
    @RequestMapping(value = "/swagger-resources/configuration/ui",
        produces = { "*/*" }, 
        method = RequestMethod.OPTIONS)
    ResponseEntity<UiConfiguration> uiConfiguration6();

}

